# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 23:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('game_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('game_name', models.CharField(max_length=200)),
                ('game_emoji', models.CharField(max_length=200)),
                ('game_created', models.DateTimeField(auto_now_add=True)),
                ('game_updated', models.DateTimeField(auto_now=True)),
                ('game_saved', models.BooleanField(default=False)),
                ('game_featured', models.BooleanField(default=False)),
                ('game_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-game_created'],
            },
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplay_uid', models.CharField(default=uuid.uuid4, max_length=40)),
                ('game_created', models.DateTimeField(auto_now_add=True)),
                ('game_updated', models.DateTimeField(auto_now=True)),
                ('game_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plqst.Game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
